### ISSUE TITLE
Download fail when uploading the release to Micro BOSH

### ISSUE THREAD

**Issue by 0xd3adcafe** [cloudfoundry-attic/bosh-sample-release#1]
Follow the instructions from here: http://cloudfoundry.github.com/docs/running/deploying-cf/openstack/install_wordpress_openstack.html

```
root@inception:/var/vcap/releases/bosh-sample-release# bosh upload release releases/wordpress-1.yml

Copying packages
----------------
apache2 (1)                   FOUND REMOTE
Downloading c12ebc02-3eb0-4fce-9d85-47fe713ed3dd...
common (1)                    FOUND REMOTE
Downloading 7248604a-8288-4056-8216-4b62171082d2...
at depth 1 - 19: self signed certificate in certificate chain
/usr/local/rvm/gems/ruby-1.9.3-p385/gems/blobstore_client-0.5.0/lib/blobstore_client/s3_blobstore_client.rb:105:in `rescue in get_file': uninitialized constant AWS::S3::NoSuchKey (NameError)
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/blobstore_client-0.5.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/blobstore_client-0.5.0/lib/blobstore_client/base.rb:51:in `get'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/release_compiler.rb:150:in `find_in_indices'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/release_compiler.rb:109:in `find_package'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/release_compiler.rb:59:in `block in compile'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/release_compiler.rb:53:in `each'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/release_compiler.rb:53:in `compile'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/commands/release.rb:211:in `upload_manifest'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/commands/release.rb:115:in `upload'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/command_handler.rb:57:in `run'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/runner.rb:58:in `run'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/lib/cli/runner.rb:18:in `run'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/gems/bosh_cli-1.0.3/bin/bosh:16:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/bin/bosh:23:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p385/bin/bosh:23:in `<main>'
```

**Comment by frodenas** [comment]
It should be an S3 transient error. Just downloaded it right now and it's working for me. Can you please try it again?

**Comment by 0xd3adcafe** [comment]
Download complete after retry 34 times. <3 .
